name: iOS CI with Fastlane (SPM)

on:
  push:
    branches: [ quik ]
  pull_request:
    branches: [ quik ]

jobs:
  ios-ci:
    name: Run iOS CI
    runs-on: macos-14  # 🆕 Esto te da Swift 6.1 por defecto


    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
     
      - name: 🧰 Install Swift 6.1
        run: |
          curl -L -o swift.pkg https://download.swift.org/swift-6.1-release/xcode/swift-6.1-RELEASE/swift-6.1-RELEASE-osx.pkg
          sudo installer -pkg swift.pkg -target /
          rm swift.pkg

      - name: ✅ Verify Swift version
        run: swift --version
  
      - name: 💎 Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: false # usamos cache manual

      - name: 💾 Cache vendor/bundle
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: 📦 Install Fastlane and Ruby deps
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: 🚀 Run Fastlane lane
        run: |
          USE_SWIFTLINT=true SCHEME=NombreDeTuEsquema IS_SPM=true bundle exec fastlane ios ci
